{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ce5e91f4-e761-463d-9de6-ac65c04b43a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-23 16:18:37.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.038 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.038 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.060 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.060 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.072 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.072 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-23 16:18:37.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# 导入 Streamlit 库，用于构建 Web 应用\n",
    "import streamlit as st\n",
    "\n",
    "# 导入 joblib 库，用于加载和保存机器学习模型\n",
    "import joblib\n",
    "\n",
    "# 导入 NumPy 库，用于数值计算\n",
    "import numpy as np\n",
    "\n",
    "# 导入 Pandas 库，用于数据处理和操作\n",
    "import pandas as pd\n",
    "\n",
    "# 导入 SHAP 库，用于解释机器学习模型的预测\n",
    "import shap\n",
    "\n",
    "# 导入 Matplotlib 库，用于数据可视化\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "# 加载训练好的模型（GBD.pkl）\n",
    "model = joblib.load('D:/桌面/科研/周亮模型/网页模型/GBD.pkl')\n",
    "\n",
    "\n",
    "# 从 X_test.csv 文件加载测试数据，以便用于 LIME 解释器\n",
    "X_test = pd.read_csv(\"D:/桌面/科研/周亮模型/网页模型/lasso_data.csv\", encoding='gbk')\n",
    "\n",
    "# 定义特征名称，对应数据集中的列名\n",
    "feature_names = [\"性别\",\t\n",
    "                 \"年龄\",\n",
    "                 \"体质指数\",\n",
    "                 \"甘油三酯\",\n",
    "                 \"低密度脂蛋白胆固醇\",\n",
    "                 \"高密度脂蛋白胆固醇\",\n",
    "                 \"谷丙转氨酶\",\n",
    "                 \"谷草酶谷丙酶\",\n",
    "                 \"总蛋白\",\n",
    "                 \"白蛋白\",\n",
    "                 \"血肌酐\",\n",
    "                 \"血尿酸\",\n",
    "                 \"空腹血糖\",\n",
    "                 \"白细胞\",\n",
    "                 \"淋巴细胞计数\",\n",
    "                 \"平均血红蛋白\",\n",
    "                 \"血小板\"\n",
    "]\n",
    "\n",
    "\n",
    "# StreamLit 用户界面\n",
    "st.title(\"脂肪肝预测器\")  # 设置网页标题\n",
    "\n",
    "# 年龄：数值输入框\n",
    "年龄 = st.number_input(\"年龄:\", min_value=0, max_value=120, value=41)\n",
    "\n",
    "# 性别：分类选择框（0：女性，1：男性）\n",
    "性别 = st.selectbox(\"性别:\", options=[0, 1], format_func=lambda x: \"男\" if x == 1 else \"女\")\n",
    "\n",
    "体质指数 = st.number_input(\"体质指数:\", min_value=0, max_value=30, value=23)\n",
    "\n",
    "\n",
    "甘油三酯 = st.number_input(\"甘油三酯:\", min_value=0.1, max_value=20.0, value=1.5, step=0.1)\n",
    "\n",
    "\n",
    "低密度脂蛋白胆固醇 = st.number_input(\"低密度脂蛋白胆固醇:\", min_value=0.5,\n",
    "        max_value=10.0,\n",
    "        value=2.3,\n",
    "        step=0.1)\n",
    "\n",
    "\n",
    "高密度脂蛋白胆固醇 = st.number_input(\"高密度脂蛋白胆固醇:\", min_value=0.1,\n",
    "        max_value=5.0,\n",
    "        value=1.2,\n",
    "        step=0.1)\n",
    "\n",
    "\n",
    "谷丙转氨酶 = st.number_input(\"谷丙转氨酶:\",  min_value=0,\n",
    "        max_value=500,\n",
    "        value=20,\n",
    "        step=1)\n",
    "\n",
    "\n",
    "谷草酶谷丙酶 = st.number_input(\"谷草酶谷丙酶:\",  min_value=0.1,\n",
    "        max_value=5.0,\n",
    "        value=1.0,\n",
    "        step=0.1)\n",
    "\n",
    "\n",
    "总蛋白 = st.number_input(\"总蛋白:\", min_value=40,\n",
    "        max_value=100,\n",
    "        value=70,\n",
    "        step=1)\n",
    "\n",
    "\n",
    "白蛋白 = st.number_input(\"白蛋白:\", min_value=20,\n",
    "        max_value=70,\n",
    "        value=45,\n",
    "        step=1)\n",
    "\n",
    "血肌酐 = st.number_input(\"血肌酐:\", min_value=10,\n",
    "        max_value=500,\n",
    "        value=70,\n",
    "        step=1)\n",
    "\n",
    "\n",
    "血尿酸 = st.number_input(\"血尿酸:\", min_value=50,\n",
    "        max_value=1000,\n",
    "        value=300,\n",
    "        step=1)\n",
    "\n",
    "\n",
    "空腹血糖 = st.number_input(\"空腹血糖:\", min_value=2.0,\n",
    "        max_value=20.0,\n",
    "        value=5.0,\n",
    "        step=0.1)\n",
    "\n",
    "白细胞 = st.number_input(\"白细胞:\", min_value=1.0,\n",
    "        max_value=30.0,\n",
    "        value=7.0,\n",
    "        step=0.1)\n",
    "\n",
    "淋巴细胞计数 = st.number_input(\"淋巴细胞计数:\", min_value=0.1,\n",
    "        max_value=10.0,\n",
    "        value=2.0,\n",
    "        step=0.1)\n",
    "\n",
    "平均血红蛋白 = st.number_input(\"平均血红蛋白:\", min_value=20,\n",
    "        max_value=50,\n",
    "        value=30,\n",
    "        step=1)\n",
    "\n",
    "血小板 = st.number_input(\"血小板:\", min_value=20,\n",
    "        max_value=1000,\n",
    "        value=200,\n",
    "        step=1)\n",
    "# 处理输入数据并进行预测\n",
    "feature_values = [性别,年龄,体质指数,甘油三酯,低密度脂蛋白胆固醇,高密度脂蛋白胆固醇,谷丙转氨酶,谷草酶谷丙酶,总蛋白,白蛋白,血肌酐,\n",
    "                  血尿酸,空腹血糖,白细胞,淋巴细胞计数,平均血红蛋白,血小板]  # 将用户输入的特征值存入列表\n",
    "features = np.array([feature_values])  # 将特征转换为 NumPy 数组，适用于模型输入\n",
    "\n",
    "# 当用户点击 \"Predict\" 按钮时执行以下代码\n",
    "if st.button(\"Predict\"):\n",
    "    # 预测类别（0：无心脏病，1：有心脏病）\n",
    "    predicted_class = model.predict(features)[0]\n",
    "    # 预测类别的概率\n",
    "    predicted_proba = model.predict_proba(features)[0]\n",
    "\n",
    "    # 显示预测结果\n",
    "    st.write(f\"**Predicted Class:** {predicted_class} (1: Disease, 0: No Disease)\")\n",
    "    st.write(f\"**Prediction Probabilities:** {predicted_proba}\")\n",
    "\n",
    "\n",
    "    # 根据预测结果生成建议\n",
    "    probability = predicted_proba[predicted_class] * 100\n",
    "    # 如果预测类别为 1（高风险）\n",
    "    if predicted_class == 1:\n",
    "        advice = (\n",
    "            f\"According to our model, you have a high risk of heart disease. \"\n",
    "            f\"The model predicts that your probability of having heart disease is {probability:.1f}%. \"\n",
    "            \"It's advised to consult with your healthcare provider for further evaluation and possible intervention.\"\n",
    "        )\n",
    "    # 如果预测类别为 0（低风险）\n",
    "    else:\n",
    "        advice = (\n",
    "            f\"According to our model, you have a low risk of heart disease. \"\n",
    "            f\"The model predicts that your probability of not having heart disease is {probability:.1f}%. \"\n",
    "            \"However, maintaining a healthy lifestyle is important. Please continue regular check-ups with your healthcare provider.\"\n",
    "        )\n",
    "    # 显示建议\n",
    "    st.write(advice)\n",
    "\n",
    "\n",
    "    # SHAP 解释\n",
    "    st.subheader(\"SHAP Force Plot Explanation\")\n",
    "    # 创建 SHAP 解释器，基于树模型（如随机森林）\n",
    "    explainer_shap = shap.TreeExplainer(model)\n",
    "    # 计算 SHAP 值，用于解释模型的预测\n",
    "    shap_values = explainer_shap.shap_values(pd.DataFrame([feature_values], columns=feature_names))\n",
    "\n",
    "    # 根据预测类别显示 SHAP 强制图\n",
    "    if predicted_class == 1:\n",
    "        shap.force_plot(explainer_shap.expected_value[1], shap_values[...,1], pd.DataFrame([feature_values], columns=feature_names), matplotlib=True)\n",
    "    else:\n",
    "        shap.force_plot(explainer_shap.expected_value[0], shap_values[...,0], pd.DataFrame([feature_values], columns=feature_names), matplotlib=True)\n",
    "\n",
    "    plt.savefig(\"shap_force_plot.png\", bbox_inches='tight', dpi=1200)\n",
    "    st.image(\"shap_force_plot.png\", caption='SHAP Force Plot Explanation')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c04e6e65-f929-4967-b7c3-c9650b5bd473",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "安装成功！\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cddad89c-3746-4ad2-a187-3f2a0675520f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
