{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": none,
   "id": "3d04f1f4-f9e7-4c47-9f6e-b42bfb2e1b64",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 导入 Streamlit 库，用于构建 Web 应用\n",
    "import streamlit as st\n",
    "\n",
    "# 导入 joblib 库，用于加载和保存机器学习模型\n",
    "import joblib\n",
    "\n",
    "# 导入 NumPy 库，用于数值计算\n",
    "import numpy as np\n",
    "\n",
    "# 导入 Pandas 库，用于数据处理和操作\n",
    "import pandas as pd\n",
    "\n",
    "# 导入 SHAP 库，用于解释机器学习模型的预测\n",
    "import shap\n",
    "\n",
    "# 导入 Matplotlib 库，用于数据可视化\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# -------------------------- 关键：解决Matplotlib中文乱码 --------------------------\n",
    "plt.rcParams[\"font.family\"] = [\"SimHei\", \"WenQuanYi Micro Hei\", \"Heiti TC\"]  # 支持中文\n",
    "plt.rcParams[\"axes.unicode_minus\"] = False  # 解决负号显示问题\n",
    "\n",
    "# -------------------------- 加载模型（确保是树模型，支持predict_proba） --------------------------\n",
    "model = joblib.load('D:/桌面/科研/周亮模型/网页模型/GBD.pkl')\n",
    "\n",
    "# -------------------------- 定义特征名称（需和模型训练时的顺序一致） --------------------------\n",
    "feature_names = [\n",
    "    \"性别\", \"年龄\", \"体质指数\", \"甘油三酯\", \"低密度脂蛋白胆固醇\",\n",
    "    \"高密度脂蛋白胆固醇\", \"谷丙转氨酶\", \"谷草酶谷丙酶\", \"总蛋白\", \"白蛋白\",\n",
    "    \"血肌酐\", \"血尿酸\", \"空腹血糖\", \"白细胞\", \"淋巴细胞计数\",\n",
    "    \"平均血红蛋白\", \"血小板\"\n",
    "]\n",
    "\n",
    "# -------------------------- StreamLit 用户界面 --------------------------\n",
    "st.title(\"脂肪肝预测器\")  # 设置网页标题\n",
    "\n",
    "# 性别：分类选择框（0：女性，1：男性）\n",
    "性别 = st.selectbox(\"性别:\", options=[0, 1], format_func=lambda x: \"男\" if x == 1 else \"女\")\n",
    "\n",
    "# 年龄：数值输入框\n",
    "年龄 = st.number_input(\"年龄:\", min_value=0, max_value=120, value=41, step=1)\n",
    "\n",
    "# 体质指数（BMI）：修正参数（浮点数、合理范围）\n",
    "体质指数 = st.number_input(\"体质指数:\", min_value=10.0, max_value=50.0, value=23.0, step=0.1)\n",
    "\n",
    "# 甘油三酯\n",
    "甘油三酯 = st.number_input(\"甘油三酯:\", min_value=0.1, max_value=20.0, value=1.5, step=0.1)\n",
    "\n",
    "# 低密度脂蛋白胆固醇\n",
    "低密度脂蛋白胆固醇 = st.number_input(\n",
    "    \"低密度脂蛋白胆固醇:\",\n",
    "    min_value=0.5, max_value=10.0, value=2.3, step=0.1\n",
    ")\n",
    "\n",
    "# 高密度脂蛋白胆固醇\n",
    "高密度脂蛋白胆固醇 = st.number_input(\n",
    "    \"高密度脂蛋白胆固醇:\",\n",
    "    min_value=0.1, max_value=5.0, value=1.2, step=0.1\n",
    ")\n",
    "\n",
    "# 谷丙转氨酶\n",
    "谷丙转氨酶 = st.number_input(\n",
    "    \"谷丙转氨酶:\", min_value=0, max_value=500, value=20, step=1\n",
    ")\n",
    "\n",
    "# 谷草酶谷丙酶\n",
    "谷草酶谷丙酶 = st.number_input(\n",
    "    \"谷草酶谷丙酶:\", min_value=0.1, max_value=5.0, value=1.0, step=0.1\n",
    ")\n",
    "\n",
    "# 总蛋白\n",
    "总蛋白 = st.number_input(\"总蛋白:\", min_value=40, max_value=100, value=70, step=1)\n",
    "\n",
    "# 白蛋白\n",
    "白蛋白 = st.number_input(\"白蛋白:\", min_value=20, max_value=70, value=45, step=1)\n",
    "\n",
    "# 血肌酐\n",
    "血肌酐 = st.number_input(\"血肌酐:\", min_value=10, max_value=500, value=70, step=1)\n",
    "\n",
    "# 血尿酸\n",
    "血尿酸 = st.number_input(\"血尿酸:\", min_value=50, max_value=1000, value=300, step=1)\n",
    "\n",
    "# 空腹血糖\n",
    "空腹血糖 = st.number_input(\"空腹血糖:\", min_value=2.0, max_value=20.0, value=5.0, step=0.1)\n",
    "\n",
    "# 白细胞\n",
    "白细胞 = st.number_input(\"白细胞:\", min_value=1.0, max_value=30.0, value=7.0, step=0.1)\n",
    "\n",
    "# 淋巴细胞计数\n",
    "淋巴细胞计数 = st.number_input(\n",
    "    \"淋巴细胞计数:\", min_value=0.1, max_value=10.0, value=2.0, step=0.1\n",
    ")\n",
    "\n",
    "# 平均血红蛋白\n",
    "平均血红蛋白 = st.number_input(\"平均血红蛋白:\", min_value=20, max_value=50, value=30, step=1)\n",
    "\n",
    "# 血小板\n",
    "血小板 = st.number_input(\"血小板:\", min_value=20, max_value=1000, value=200, step=1)\n",
    "\n",
    "# -------------------------- 处理输入数据 --------------------------\n",
    "feature_values = [\n",
    "    性别, 年龄, 体质指数, 甘油三酯, 低密度脂蛋白胆固醇,\n",
    "    高密度脂蛋白胆固醇, 谷丙转氨酶, 谷草酶谷丙酶, 总蛋白, 白蛋白,\n",
    "    血肌酐, 血尿酸, 空腹血糖, 白细胞, 淋巴细胞计数,\n",
    "    平均血红蛋白, 血小板\n",
    "]\n",
    "# 转换为DataFrame（SHAP需要列名，更规范）\n",
    "features_df = pd.DataFrame([feature_values], columns=feature_names)\n",
    "features = np.array([feature_values])\n",
    "\n",
    "# -------------------------- 预测逻辑 --------------------------\n",
    "if st.button(\"预测\"):\n",
    "    try:\n",
    "        # 预测类别和概率\n",
    "        predicted_class = model.predict(features)[0]\n",
    "        predicted_proba = model.predict_proba(features)[0]\n",
    "\n",
    "        # -------------------------- 显示预测结果（修正为脂肪肝业务逻辑） --------------------------\n",
    "        st.subheader(\"预测结果\")\n",
    "        class_desc = \"有脂肪肝\" if predicted_class == 1 else \"无脂肪肝\"\n",
    "        st.write(f\"**预测类别：** {predicted_class}（{class_desc}）\")\n",
    "        st.write(f\"**预测概率：** 无脂肪肝：{predicted_proba[0]:.4f}，有脂肪肝：{predicted_proba[1]:.4f}\")\n",
    "\n",
    "        # 生成个性化建议（修正为脂肪肝相关）\n",
    "        probability = predicted_proba[predicted_class] * 100\n",
    "        if predicted_class == 1:\n",
    "            advice = (\n",
    "                f\"根据模型预测，你有**高风险患脂肪肝**（概率：{probability:.1f}%）。\\n\"\n",
    "                \"建议：控制体重（BMI）、减少高脂高糖食物摄入、戒酒、增加运动，及时就医检查肝功能。\"\n",
    "            )\n",
    "        else:\n",
    "            advice = (\n",
    "                f\"根据模型预测，你**患脂肪肝的风险较低**（概率：{probability:.1f}%）。\\n\"\n",
    "                \"建议：保持健康饮食和运动习惯，定期体检，监测肝功能指标。\"\n",
    "            )\n",
    "        st.write(f\"**健康建议：** {advice}\")\n",
    "\n",
    "        # -------------------------- SHAP解释（优化为交互式+静态双版本） --------------------------\n",
    "        st.subheader(\"模型预测解释（SHAP Force Plot）\")\n",
    "        # 1. 初始化SHAP解释器（树模型专用）\n",
    "        explainer_shap = shap.TreeExplainer(model)\n",
    "        # 2. 计算SHAP值\n",
    "        shap_values = explainer_shap.shap_values(features_df)\n",
    "\n",
    "        # 3. 方式1：交互式SHAP Force Plot（推荐，保留交互性）\n",
    "        try:\n",
    "            shap_html = shap.force_plot(\n",
    "                explainer_shap.expected_value[1],  # 正类的期望价值\n",
    "                shap_values[1],  # 正类的SHAP值\n",
    "                features_df,\n",
    "                matplotlib=False,\n",
    "                show=False\n",
    "            )\n",
    "            # 用Streamlit显示HTML\n",
    "            st.components.v1.html(shap_html.html(), height=200, scrolling=True)\n",
    "        except:\n",
    "            # 方式2：静态Matplotlib图（备用）\n",
    "            plt.clf()  # 清理画布\n",
    "            if predicted_class == 1:\n",
    "                shap.force_plot(\n",
    "                    explainer_shap.expected_value[1],\n",
    "                    shap_values[1],\n",
    "                    features_df,\n",
    "                    matplotlib=True,\n",
    "                    show=False\n",
    "                )\n",
    "            else:\n",
    "                shap.force_plot(\n",
    "                    explainer_shap.expected_value[0],\n",
    "                    shap_values[0],\n",
    "                    features_df,\n",
    "                    matplotlib=True,\n",
    "                    show=False\n",
    "                )\n",
    "            plt.tight_layout()\n",
    "            plt.savefig(\"shap_force_plot.png\", bbox_inches='tight', dpi=300)\n",
    "            st.image(\"shap_force_plot.png\", caption=\"SHAP Force Plot 解释\")\n",
    "            plt.clf()  # 再次清理画布\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"预测过程中出现错误：{str(e)}\")\n",
    "        st.info(\"请检查：1.模型是否为树模型；2.模型是否支持predict_proba；3.特征顺序是否和训练时一致。\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
